---
- name: Copy the bind_exporter systemd service file
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart bind_exporter
