---
- name: Copy the bind_exporter systemd service file
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart bind_exporter

- name: Allow bind_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ bind_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
