---
- import_tasks: preflight.yml
  tags:
    - bind_exporter_install
    - bind_exporter_configure
    - bind_exporter_run

- import_tasks: install.yml
  become: true
  when: (not __bind_exporter_is_installed.stat.exists) or (__bind_exporter_current_version_output.stdout_lines[0].split(" ")[2] != bind_exporter_version)
  tags:
    - bind_exporter_install

- import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"
  tags:
    - bind_exporter_configure

- import_tasks: configure.yml
  become: true
  tags:
    - bind_exporter_configure

- name: Ensure bind_exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: bind_exporter
    enabled: true
    state: started
  tags:
    - bind_exporter_run
